// src/core/app.jsx
import React from 'react';
import { Route, Switch } from "wouter";

import LegoEditor from 'view/editor.v1/editor.v1.module.jsx';
import LegoRender from 'view/render.v1/render.v1.module.jsx';


function App() {
    return (
        <React.StrictMode>
            <Switch>
                <Route path="/lego/editor" component={LegoEditor} />
                <Route path="/lego/v1/:unique" component={LegoRender} />
                <Route>
                    <div>404</div>
                </Route>
            </Switch>
        </React.StrictMode>
    );
}

export default App;

// src/core/app.svelte
<script>
    import { Route } from "tinro";

    import PageEditor from "../view/page.editor.v2.svelte";
    import PageViewer from "../view/page.viewer.v1.svelte";

</script>

<Route>
    <Route path="/editor">
        <PageEditor />
    </Route>
    <Route path="/lego/v1/:unique" let:meta>
        <PageViewer unique={meta.params.unique} />
    </Route>
    <Route path="/">
        <ul>
            <li>
                <a href="/editor">Editor</a>
            </li>
            <li>
                <a href="/viewer">Viewer</a>
            </li>
        </ul>
    </Route>
    <Route fallback>
        <div>404</div>
    </Route>
</Route>
